name: CD with Docker and Railway

on:
  push:
    branches:
      - main # Виконується на змінах у гілці main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Клонуємо репозиторій
      - name: Checkout repository
        uses: actions/checkout@v3

      # Логін до Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Створення Docker-образу
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # Завантаження Docker-образу до Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Деплой через Railway (через Docker образ)
      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway link # Прив'язуємо проект Railway
          railway up --docker-image ${{ secrets.DOCKER_USERNAME }}/my-app:latest
